homepage:
    pattern: /
    defaults: { _controller: DTLTrainerBundle:Session:index, _format: html }

session_new:
    pattern: /session/new
    defaults: { _controller: DTLTrainerBundle:Session:new }

sessions:
    pattern: /sessions
    defaults: { _controller: DTLTrainerBundle:Session:index, _format: html }

sessions_rss:
    pattern: /sessions/rss
    defaults: { _controller: DTLTrainerBundle:Session:index, _format: rss }

session_edit:
    pattern: /session/{session_id}/edit
    defaults: { _controller: DTLTrainerBundle:Session:edit }

session_view:
    pattern: /session/{session_id}
    defaults: { _controller: DTLTrainerBundle:Session:view }

session_delete:
    pattern: /session/{session_id}/delete
    defaults: { _controller: DTLTrainerBundle:Session:delete }

routes:
    pattern: /routes
    defaults: { _controller: DTLTrainerBundle:Route:index }

route_new:
    pattern: /route/new
    defaults: { _controller: DTLTrainerBundle:Route:new }

route_edit:
    pattern: /route/{route_id}/edit
    defaults: { _controller: DTLTrainerBundle:Route:edit }

route_copy:
    pattern: /route/{route_id}/copy
    defaults: { _controller: DTLTrainerBundle:Route:copy }

route_delete:
    pattern: /route/{route_id}/delete
    defaults: { _controller: DTLTrainerBundle:Route:delete }

route_view:
    pattern: /route/{route_id}
    defaults: { _controller: DTLTrainerBundle:Route:view }

route_new_session:
    pattern: /route/{route_id}/session/new
    defaults: { _controller: DTLTrainerBundle:Route:newSession }

filter_update:
    pattern: /filter/update
    defaults: { _controller: DTLTrainerBundle:Filter:update }

preferences:
    pattern: /user/preferences
    defaults: { _controller: DTLTrainerBundle:User:preferences }

calendar_xml:
    pattern: /calendar/xml
    defaults: { _controller: DTLTrainerBundle:Calendar:index, _format: xml }

calendar:
    pattern: /calendar
    defaults: { _controller: DTLTrainerBundle:Calendar:index }

weight_index:
    pattern: /weight
    defaults: { _controller: DTLTrainerBundle:Weight:index }

weight_delete:
    pattern: /weight/{weight_id}/delete
    defaults: { _controller: DTLTrainerBundle:Weight:delete }
